config/routes.rb
Rails.application.routes.draw do
  get 'fertilizing_events/create'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get 'plants/:id/care', to: 'plants#care', as: :care

  resources :plants do
    resources :watering_events, only: [ :new, :create ]
    resources :fertilizing_events, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fertilizer_notification.rb
class FertilizerNotification < ApplicationRecord
  belongs_to :plant

  has_one :user, through: :plant

  validates :date, presence: true
end

app/models/fertilizing_event.rb
class FertilizingEvent < ApplicationRecord
  belongs_to :plant

  validates :date, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  extend FriendlyId
  friendly_id :common_name, use: :slugged

  has_one_attached :photo

  validates :watering_interval, presence: true

  has_many :watering_events, dependent: :destroy
  has_many :fertilizing_events, dependent: :destroy
  has_many :fertilizer_notifications, dependent: :destroy
  has_many :water_notifications, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :plants, dependent: :destroy
  has_many :watering_events, through: :plants, dependent: :destroy
  has_many :fertilizing_events, through: :plants, dependent: :destroy
  has_many :fertilizer_notifications, through: :plants, dependent: :destroy
  has_many :water_notifications, through: :plants, dependent: :destroy
end

app/models/water_notification.rb
class WaterNotification < ApplicationRecord
  belongs_to :plant

  validates :date, presence: true
end

app/models/watering_event.rb
class WateringEvent < ApplicationRecord
  belongs_to :plant

  validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || plants_path
  end
end

app/controllers/fertilizing_events_controller.rb
class FertilizingEventsController < ApplicationController
  def create
    @fertilizing_event = FertilizingEvent.new(fertilizing_event_params)
    @plant = Plant.find(params[:plant_id])
    @fertilizing_event.plant = @plant
    redirect_to plant_path(@plant) if @fertilizing_event.save
  end

  private

  def fertilizing_event_params
    params.require(:fertilizing_event).permit(:date, :note)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :destroy, :care]

  def index
    @plants = Plant.includes(:watering_events).where(user: current_user)
    upcoming_events = current_user.fertilizer_notifications.where("date > ?", Date.today - 7) +
                      current_user.water_notifications.where("date > ?", Date.today - 7)
    @sorted_upcoming_events = upcoming_events.sort_by(&:date)
  end

  def show
    @watering_event = WateringEvent.new
    @fertilizing_event = FertilizingEvent.new
  end

  def new
    @plant = Plant.new
  end

  def create
    plant = Plant.new(plant_params)
    plant.user = current_user
    if plant.save
      redirect_to plant_path(plant)
    else
      render :new
    end
  end

  def destroy
    redirect_to root_path if @plant.destroy
  end

  def care
    past_events = @plant.watering_events + @plant.fertilizing_events
    @sorted_past_events = past_events.sort_by(&:date)
  end

  private

  def set_plant
    @plant = Plant.friendly.find(params[:id])
  end

  def plant_params
    params.require(:plant).permit(:common_name, :nickname, :watering_interval, :fertilizing_interval, :photo)
  end
end

app/controllers/watering_events_controller.rb
class WateringEventsController < ApplicationController
  def create
    @watering_event = WateringEvent.new(watering_event_params)
    @plant = Plant.find(params[:plant_id])
    @watering_event.plant = @plant
    redirect_to plant_path(@plant) if @watering_event.save
  end

  private

  def watering_event_params
    params.require(:watering_event).permit(:date, :note)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fertilizing_events/create.html.erb
<h1>FertilizingEvents#create</h1>
<p>Find me in app/views/fertilizing_events/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WaterYourPlants</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>
  <% if user_signed_in? %>
   <%= render 'shared/navbar' %>
  <% end %>
  <%= render 'shared/flashes' %>

  <%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Helloooo</h1>

app/views/plants/care.html.erb
<div class="container">
  <div class="header">
    <p><%= @plant.common_name %></p>
  </div>
  <% if @sorted_past_events.present? %>
      <div class="container-cards">
      <% @sorted_past_events.each do |event| %>
        <% case event.class.name
           when "FertilizingEvent" %>
          <div class="care-card-water">
            <div class="care-card-text">
            <% if event.date == Date.today %>
              <p>Fertilized today</p>
            <% elsif event.date < Date.today - 7 %>
              <p>Fertilized on: <%= event.date.strftime("%B %d") %></p>
            <% else %>
              <p>Fertilized <%= pluralize((Date.today - event.date).to_i, "days")%> ago</p>
            <% end %>
            </div>
          </div>
          <% when "WateringEvent" %>
          <div class="care-card-fertilizer">
            <div class="care-card-text">
            <% if event.date == Date.today %>
              <p>Watered today</p>
            <% elsif event.date < Date.today - 7 %>
              <p>Watered on: <%= event.date.strftime("%B %d") %></p>
            <% else %>
              <p>Watered <%= pluralize((Date.today - event.date).to_i, "days")%> ago</p>
            <% end %>
            </div>
          </div>
      <% end %>
    <% end %>
      </div>
  <% end %>
</div>

app/views/plants/index.html.erb
<div class="container-index">
  <div class="overview">
    <h5>Hello <%= current_user.name.capitalize %>,</h5>
    <p>TESTeeeeeee 🌱</p>
  </div>
  <% if @plants.present? %>
  <p style="margin-left: 20px;">Your Garden has <%= pluralize(@plants.count, "plant") %>.</p>
    <div class="scrollable">
      <% @plants.each do |plant| %>
        <%= link_to plant_path(plant) do %>
          <div class="plant-card shadow p-3 mb-5 bg-white rounded">
            <div class="plant-card-text">
              <p style="font-weight: bold;"><%= plant.common_name %></p>
            </div>
          </div>
        <% end %>
     <% end %>
    </div>
    <p style="margin-left: 20px;">Upcoming activites:</p>
    <div class="scrollable">
        <% @sorted_upcoming_events.each do |event| %>
        <%= link_to care_path(event.plant) do %>
            <% case event.class.name
               when "FertilizerNotification" %>
              <div class="fertilizer-activity-card shadow p-3 mb-5 bg-white rounded">
                <div class="plant-card-text">
                    <% if event.date == Date.today %>
                      <p>Fertilize today</p>
                    <% else %>
                      <p>Fertilize in <%= pluralize((event.date - Date.today).to_i, "days") %></p>
                    <% end %>
                  <p><%= event.plant.common_name %></p>
              </div>
            </div>
            <% when "WaterNotification" %>
              <div class="water-activity-card shadow p-3 mb-5 bg-white rounded">
                <div class="plant-card-text">
                    <% if event.date == Date.today %>
                      <p> Water today </p>
                    <% else %>
                      <p>Water in <%= pluralize((event.date - Date.today).to_i, "days") %></p>
                    <% end %>
                      <p><%= event.plant.common_name %></p>
                    </div>
                  </div>
                  <% end %>
            <% end %>
          <% end %>
      </div>
  <% else %>
  <%= link_to new_plant_path do %>
    <div class="new-plant-card">
      <div class="new-plant-text">
        <p style="color:white">Add plant</p>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/plants/new.html.erb
<div class="container-new-plant">
  <%= simple_form_for(@plant) do |f| %>
    <%= f.label :common_name %>
    <%= f.text_field :common_name %>
    <%= f.label :watering_interval %>
    <%= f.text_field :watering_interval %>
    <%= f.label :fertilizing_interval %>
    <%= f.text_field :fertilizing_interval %>
    <%= f.submit :"Add Plant", class: "btn btn-login" %>
  <% end %>
</div>

app/views/plants/show.html.erb
<div class="container-plant-show">
  <div class="block">
  <div class="plant-information">
  <p><%= @plant.common_name %></p>
  <p>Nickname: <%= @plant.nickname %></p>
  <p>Current watering interval: <%= @plant.watering_interval %> days</p>
  <p>Current fertilizing interval: <%= @plant.fertilizing_interval %> days</p>

  <%= link_to "Go to care plan", care_path(@plant) %>

  <%= simple_form_for([@plant, @watering_event]) do |f| %>
    <%= f.label :date %>
    <%= f.text_field :date %>
    <%= f.label :note %>
    <%= f.text_field :note %>
    <%= f.submit %>
  <% end %>

  <%= simple_form_for([@plant, @fertilizing_event]) do |f| %>
    <%= f.label :date %>
    <%= f.text_field :date %>
    <%= f.label :note %>
    <%= f.text_field :note %>
    <%= f.submit %>
  <% end %>

  <%= link_to "#{@plant.common_name} died...", plant_path(@plant), method: :delete, data: {confirm: 'Are you sure?'} %>
  </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to plants_path, class: "navbar-brand" do %>
    <% unless current_page?(plants_path) %>
      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-left" width="40" height="40" viewBox="0 0 24 24" stroke-width="1" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z"/>
        <polyline points="15 6 9 12 15 18" />
      </svg>
    <% end %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-align-right" width="40" height="40" viewBox="0 0 24 24" stroke-width="1" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
    <path stroke="none" d="M0 0h24v24H0z"/>
    <line x1="4" y1="6" x2="20" y2="6" />
    <line x1="10" y1="12" x2="20" y2="12" />
    <line x1="6" y1="18" x2="20" y2="18" />
    </svg>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
          <%= link_to "Add a plant", new_plant_path, class: "dropdown-item" %>
          <%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
      </li>
    </ul>
  </div>
</div>